// corpus.json is generated by build_corpus.py and bundled at deploy time by
// wrangler's esbuild. Declaring the shape here (instead of resolveJsonModule)
// keeps `tsc --noEmit` working before the file has been generated, and keeps
// TypeScript from trying to infer a type from ~180KB of base64.
declare module "*.json" {
  const corpus: {
    embedModel: string;
    dim: number;
    queryPrefix: string;
    /** Base64 of a row-major, L2-normalized Float32Array of shape [chunks, dim]. */
    embeddings: string;
    chunks: { text: string; meta: Record<string, unknown> }[];
  };
  export default corpus;
}
